defaultBaseImage: gcr.io/distroless/static:nonroot
builds:
  - id: osv-mcp-server
    dir: .
    main: ./cmd/server
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w