builds:
- id: osv-mcp-server
  dir: .
  main: ./cmd/server
  env:
    - CGO_ENABLED=0
  flags:
    - -trimpath
  ldflags:
    - -s -w
    - -X main.version={{.Env.VERSION}}
  labels:
    org.opencontainers.image.created: "{{.Env.CREATION_TIME}}"
    org.opencontainers.image.description: "osv-mcp - An OSV MCP Server"
    org.opencontainers.image.licenses: "Apache-2.0"
    org.opencontainers.image.revision: "{{.Env.GITHUB_SHA}}"
    org.opencontainers.image.source: "{{.Env.GITHUB_SERVER_URL}}/{{.Env.GITHUB_REPOSITORY}}"
    org.opencontainers.image.title: "osv-mcp"
    org.opencontainers.image.url: "{{.Env.GITHUB_SERVER_URL}}/{{.Env.GITHUB_REPOSITORY}}"
    org.opencontainers.image.version: "{{.Env.VERSION}}"
